// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: seq.sql

package repo

import (
	"context"
	"time"
)

const createSeq = `-- name: CreateSeq :exec
INSERT INTO ` + "`" + `seq` + "`" + ` (
    created_at, updated_at, object_type, object_id, seq
) VALUES (
    ?, ?, ?, ?, ?
)
`

// 创建序列号记录
func (q *Queries) CreateSeq(ctx context.Context, createdAt time.Time, updatedAt time.Time, objectType int8, objectID uint64, seq uint64) error {
	_, err := q.db.ExecContext(ctx, createSeq,
		createdAt,
		updatedAt,
		objectType,
		objectID,
		seq,
	)
	return err
}

const deleteSeq = `-- name: DeleteSeq :exec
DELETE FROM ` + "`" + `seq` + "`" + ` 
WHERE object_type = ? AND object_id = ?
`

// 删除序列号记录
func (q *Queries) DeleteSeq(ctx context.Context, objectType int8, objectID uint64) error {
	_, err := q.db.ExecContext(ctx, deleteSeq, objectType, objectID)
	return err
}

const getOrCreateSeq = `-- name: GetOrCreateSeq :exec
INSERT INTO ` + "`" + `seq` + "`" + ` (created_at, updated_at, object_type, object_id, seq)
VALUES (?, ?, ?, ?, 1)
ON DUPLICATE KEY UPDATE 
    updated_at = VALUES(updated_at),
    seq = seq + 1
`

// 获取或创建序列号（使用 INSERT ... ON DUPLICATE KEY UPDATE）
func (q *Queries) GetOrCreateSeq(ctx context.Context, createdAt time.Time, updatedAt time.Time, objectType int8, objectID uint64) error {
	_, err := q.db.ExecContext(ctx, getOrCreateSeq,
		createdAt,
		updatedAt,
		objectType,
		objectID,
	)
	return err
}

const getSeq = `-- name: GetSeq :one
SELECT id, created_at, updated_at, object_type, object_id, seq FROM ` + "`" + `seq` + "`" + ` 
WHERE object_type = ? AND object_id = ? 
LIMIT 1
`

// 获取序列号
func (q *Queries) GetSeq(ctx context.Context, objectType int8, objectID uint64) (*Seq, error) {
	row := q.db.QueryRowContext(ctx, getSeq, objectType, objectID)
	var i Seq
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObjectType,
		&i.ObjectID,
		&i.Seq,
	)
	return &i, err
}

const incrementSeq = `-- name: IncrementSeq :exec
UPDATE ` + "`" + `seq` + "`" + ` 
SET updated_at = ?, seq = seq + 1
WHERE object_type = ? AND object_id = ?
`

// 递增序列号
func (q *Queries) IncrementSeq(ctx context.Context, updatedAt time.Time, objectType int8, objectID uint64) error {
	_, err := q.db.ExecContext(ctx, incrementSeq, updatedAt, objectType, objectID)
	return err
}

const updateSeq = `-- name: UpdateSeq :exec
UPDATE ` + "`" + `seq` + "`" + ` 
SET updated_at = ?, seq = ?
WHERE object_type = ? AND object_id = ?
`

// 更新序列号
func (q *Queries) UpdateSeq(ctx context.Context, updatedAt time.Time, seq uint64, objectType int8, objectID uint64) error {
	_, err := q.db.ExecContext(ctx, updateSeq,
		updatedAt,
		seq,
		objectType,
		objectID,
	)
	return err
}
