database:
  mysql:
    dsn: "root:azsx0123456@tcp(localhost:3307)/imserver?multiStatements=true&parseTime=true"
  redis:
    host: "localhost:6379"
    password: ""
  mongo:
    uri: "mongodb://root:example@localhost:27017"
    database: "gim"
    authSource: "admin"

jwt:
  secret: "your-super-secret-jwt-signing-key-change-in-production"
  issuer: "im-server"
  audience: "im-client"
  ttl: "24h"

services:
  gateway:
    port: 8080
  auth:
    rpc_addr: ":50051"
    local_addr: "localhost:50051"
  user:
    rpc_addr: ":50052"
    local_addr: "localhost:50052"
  friend:
    rpc_addr: ":50053"
    local_addr: "localhost:50053"
  device:
    rpc_addr: ":50054"
    local_addr: "localhost:50054"
  connect:
    rpc_addr: ":50055"
    local_addr: "localhost:50055"

broker:
  nats_url: "nats://localhost:4222"
  use_jetstream: true
