version: "3.9"

services:
  mysql:
    image: mysql:8.4
    container_name: im_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: azsx0123456
      MYSQL_DATABASE: imserver
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-pazsx0123456"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - im-net

  redis:
    image: redis:7
    container_name: im_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - im-net

  mongo:
    image: mongo:6
    container_name: im_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: gim
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - im-net

  mongo-express:
    image: mongo-express:1
    container_name: im_mongo_express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_BASICAUTH: "false"
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    networks:
      - im-net

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: im_kafka
    restart: unless-stopped
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@im_kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    ports:
      - "9092:9092"
    networks:
      - im-net

networks:
  im-net:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
  mongo_data:
    driver: local
