// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: pkg/protocol/proto/user/user.ext.proto

package userpb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 搜索用户请求
type SearchUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`                    // 搜索关键字，可以是用户名或手机号
	Page          uint32                 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`                         // 分页页码，默认从 1 开始
	PageSize      uint32                 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页返回的用户数量，默认值为 10
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUserRequest) Reset() {
	*x = SearchUserRequest{}
	mi := &file_pkg_protocol_proto_user_user_ext_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUserRequest) ProtoMessage() {}

func (x *SearchUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_proto_user_user_ext_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUserRequest.ProtoReflect.Descriptor instead.
func (*SearchUserRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_proto_user_user_ext_proto_rawDescGZIP(), []int{0}
}

func (x *SearchUserRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchUserRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchUserRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 搜索用户响应
type SearchUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserInfo            `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`  // 搜索结果中的用户列表
	Total         uint32                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // 搜索结果的总用户数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUserResponse) Reset() {
	*x = SearchUserResponse{}
	mi := &file_pkg_protocol_proto_user_user_ext_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUserResponse) ProtoMessage() {}

func (x *SearchUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_proto_user_user_ext_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUserResponse.ProtoReflect.Descriptor instead.
func (*SearchUserResponse) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_proto_user_user_ext_proto_rawDescGZIP(), []int{1}
}

func (x *SearchUserResponse) GetUsers() []*UserInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *SearchUserResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 用户信息
type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`         // 用户 ID
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`                    // 用户名
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"` // 用户头像 URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_pkg_protocol_proto_user_user_ext_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_proto_user_user_ext_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_proto_user_user_ext_proto_rawDescGZIP(), []int{2}
}

func (x *UserInfo) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserInfo) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

var File_pkg_protocol_proto_user_user_ext_proto protoreflect.FileDescriptor

const file_pkg_protocol_proto_user_user_ext_proto_rawDesc = "" +
	"\n" +
	"&pkg/protocol/proto/user/user.ext.proto\x12\x04user\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\"^\n" +
	"\x11SearchUserRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x12\n" +
	"\x04page\x18\x02 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\rR\bpageSize\"P\n" +
	"\x12SearchUserResponse\x12$\n" +
	"\x05users\x18\x01 \x03(\v2\x0e.user.UserInfoR\x05users\x12\x14\n" +
	"\x05total\x18\x02 \x01(\rR\x05total\"^\n" +
	"\bUserInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl2q\n" +
	"\x0eUserExtService\x12_\n" +
	"\n" +
	"SearchUser\x12\x17.user.SearchUserRequest\x1a\x18.user.SearchUserResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/user/searchB\x18Z\x16pkg/protocol/pb/userpbb\x06proto3"

var (
	file_pkg_protocol_proto_user_user_ext_proto_rawDescOnce sync.Once
	file_pkg_protocol_proto_user_user_ext_proto_rawDescData []byte
)

func file_pkg_protocol_proto_user_user_ext_proto_rawDescGZIP() []byte {
	file_pkg_protocol_proto_user_user_ext_proto_rawDescOnce.Do(func() {
		file_pkg_protocol_proto_user_user_ext_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_protocol_proto_user_user_ext_proto_rawDesc), len(file_pkg_protocol_proto_user_user_ext_proto_rawDesc)))
	})
	return file_pkg_protocol_proto_user_user_ext_proto_rawDescData
}

var file_pkg_protocol_proto_user_user_ext_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_protocol_proto_user_user_ext_proto_goTypes = []any{
	(*SearchUserRequest)(nil),  // 0: user.SearchUserRequest
	(*SearchUserResponse)(nil), // 1: user.SearchUserResponse
	(*UserInfo)(nil),           // 2: user.UserInfo
}
var file_pkg_protocol_proto_user_user_ext_proto_depIdxs = []int32{
	2, // 0: user.SearchUserResponse.users:type_name -> user.UserInfo
	0, // 1: user.UserExtService.SearchUser:input_type -> user.SearchUserRequest
	1, // 2: user.UserExtService.SearchUser:output_type -> user.SearchUserResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_protocol_proto_user_user_ext_proto_init() }
func file_pkg_protocol_proto_user_user_ext_proto_init() {
	if File_pkg_protocol_proto_user_user_ext_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_protocol_proto_user_user_ext_proto_rawDesc), len(file_pkg_protocol_proto_user_user_ext_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_protocol_proto_user_user_ext_proto_goTypes,
		DependencyIndexes: file_pkg_protocol_proto_user_user_ext_proto_depIdxs,
		MessageInfos:      file_pkg_protocol_proto_user_user_ext_proto_msgTypes,
	}.Build()
	File_pkg_protocol_proto_user_user_ext_proto = out.File
	file_pkg_protocol_proto_user_user_ext_proto_goTypes = nil
	file_pkg_protocol_proto_user_user_ext_proto_depIdxs = nil
}
