// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: pkg/protocol/proto/user/user.int.proto

package userpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId      uint64                 `protobuf:"varint,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_pkg_protocol_proto_user_user_int_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_proto_user_user_int_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_proto_user_user_int_proto_rawDescGZIP(), []int{0}
}

func (x *AuthRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AuthRequest) GetDeviceId() uint64 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *AuthRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_pkg_protocol_proto_user_user_int_proto protoreflect.FileDescriptor

const file_pkg_protocol_proto_user_user_int_proto_rawDesc = "" +
	"\n" +
	"&pkg/protocol/proto/user/user.int.proto\x12\x04user\x1a\x1bgoogle/protobuf/empty.proto\"Y\n" +
	"\vAuthRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\x04R\bdeviceId\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token2C\n" +
	"\x0eUserIntService\x121\n" +
	"\x04Auth\x12\x11.user.AuthRequest\x1a\x16.google.protobuf.EmptyB\x18Z\x16pkg/protocol/pb/userpbb\x06proto3"

var (
	file_pkg_protocol_proto_user_user_int_proto_rawDescOnce sync.Once
	file_pkg_protocol_proto_user_user_int_proto_rawDescData []byte
)

func file_pkg_protocol_proto_user_user_int_proto_rawDescGZIP() []byte {
	file_pkg_protocol_proto_user_user_int_proto_rawDescOnce.Do(func() {
		file_pkg_protocol_proto_user_user_int_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_protocol_proto_user_user_int_proto_rawDesc), len(file_pkg_protocol_proto_user_user_int_proto_rawDesc)))
	})
	return file_pkg_protocol_proto_user_user_int_proto_rawDescData
}

var file_pkg_protocol_proto_user_user_int_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_protocol_proto_user_user_int_proto_goTypes = []any{
	(*AuthRequest)(nil),   // 0: user.AuthRequest
	(*emptypb.Empty)(nil), // 1: google.protobuf.Empty
}
var file_pkg_protocol_proto_user_user_int_proto_depIdxs = []int32{
	0, // 0: user.UserIntService.Auth:input_type -> user.AuthRequest
	1, // 1: user.UserIntService.Auth:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_protocol_proto_user_user_int_proto_init() }
func file_pkg_protocol_proto_user_user_int_proto_init() {
	if File_pkg_protocol_proto_user_user_int_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_protocol_proto_user_user_int_proto_rawDesc), len(file_pkg_protocol_proto_user_user_int_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_protocol_proto_user_user_int_proto_goTypes,
		DependencyIndexes: file_pkg_protocol_proto_user_user_int_proto_depIdxs,
		MessageInfos:      file_pkg_protocol_proto_user_user_int_proto_msgTypes,
	}.Build()
	File_pkg_protocol_proto_user_user_int_proto = out.File
	file_pkg_protocol_proto_user_user_int_proto_goTypes = nil
	file_pkg_protocol_proto_user_user_int_proto_depIdxs = nil
}
