// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: pkg/protocol/proto/user/user.int.proto

package userpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserIntService_Auth_FullMethodName = "/user.UserIntService/Auth"
)

// UserIntServiceClient is the client API for UserIntService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserIntServiceClient interface {
	// 权限校验
	Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type userIntServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserIntServiceClient(cc grpc.ClientConnInterface) UserIntServiceClient {
	return &userIntServiceClient{cc}
}

func (c *userIntServiceClient) Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, UserIntService_Auth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserIntServiceServer is the server API for UserIntService service.
// All implementations must embed UnimplementedUserIntServiceServer
// for forward compatibility.
type UserIntServiceServer interface {
	// 权限校验
	Auth(context.Context, *AuthRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedUserIntServiceServer()
}

// UnimplementedUserIntServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserIntServiceServer struct{}

func (UnimplementedUserIntServiceServer) Auth(context.Context, *AuthRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Auth not implemented")
}
func (UnimplementedUserIntServiceServer) mustEmbedUnimplementedUserIntServiceServer() {}
func (UnimplementedUserIntServiceServer) testEmbeddedByValue()                        {}

// UnsafeUserIntServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserIntServiceServer will
// result in compilation errors.
type UnsafeUserIntServiceServer interface {
	mustEmbedUnimplementedUserIntServiceServer()
}

func RegisterUserIntServiceServer(s grpc.ServiceRegistrar, srv UserIntServiceServer) {
	// If the following call pancis, it indicates UnimplementedUserIntServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserIntService_ServiceDesc, srv)
}

func _UserIntService_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserIntServiceServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserIntService_Auth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserIntServiceServer).Auth(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserIntService_ServiceDesc is the grpc.ServiceDesc for UserIntService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserIntService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserIntService",
	HandlerType: (*UserIntServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Auth",
			Handler:    _UserIntService_Auth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/protocol/proto/user/user.int.proto",
}
