// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: pkg/protocol/proto/device/device.int.proto

package devicepb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ConnSignInRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ConnSignInRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ConnSignInRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ConnSignInRequestMultiError, or nil if none found.
func (m *ConnSignInRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ConnSignInRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for DeviceId

	// no validation rules for UserId

	// no validation rules for Token

	// no validation rules for ConnAddr

	// no validation rules for ClientAddr

	if len(errors) > 0 {
		return ConnSignInRequestMultiError(errors)
	}

	return nil
}

// ConnSignInRequestMultiError is an error wrapping multiple validation errors
// returned by ConnSignInRequest.ValidateAll() if the designated constraints
// aren't met.
type ConnSignInRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ConnSignInRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ConnSignInRequestMultiError) AllErrors() []error { return m }

// ConnSignInRequestValidationError is the validation error returned by
// ConnSignInRequest.Validate if the designated constraints aren't met.
type ConnSignInRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ConnSignInRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ConnSignInRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ConnSignInRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ConnSignInRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ConnSignInRequestValidationError) ErrorName() string {
	return "ConnSignInRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ConnSignInRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sConnSignInRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ConnSignInRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ConnSignInRequestValidationError{}

// Validate checks the field values on OfflineRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *OfflineRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OfflineRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in OfflineRequestMultiError,
// or nil if none found.
func (m *OfflineRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *OfflineRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	// no validation rules for DeviceId

	// no validation rules for ClientAddr

	if len(errors) > 0 {
		return OfflineRequestMultiError(errors)
	}

	return nil
}

// OfflineRequestMultiError is an error wrapping multiple validation errors
// returned by OfflineRequest.ValidateAll() if the designated constraints
// aren't met.
type OfflineRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OfflineRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OfflineRequestMultiError) AllErrors() []error { return m }

// OfflineRequestValidationError is the validation error returned by
// OfflineRequest.Validate if the designated constraints aren't met.
type OfflineRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OfflineRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OfflineRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OfflineRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OfflineRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OfflineRequestValidationError) ErrorName() string { return "OfflineRequestValidationError" }

// Error satisfies the builtin error interface
func (e OfflineRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOfflineRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OfflineRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OfflineRequestValidationError{}
