// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: pkg/protocol/proto/connect/connect.ext.proto

package connectpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Command int32

const (
	Command_UNKNOWN        Command = 0 // 未知
	Command_SIGN_IN        Command = 1 // 设备登录请求
	Command_SYNC           Command = 2 // 消息同步触发
	Command_HEARTBEAT      Command = 3 // 心跳
	Command_MESSAGE        Command = 4 // 消息投递
	Command_SUBSCRIBE_ROOM Command = 5 // 订阅房间
)

// Enum value maps for Command.
var (
	Command_name = map[int32]string{
		0: "UNKNOWN",
		1: "SIGN_IN",
		2: "SYNC",
		3: "HEARTBEAT",
		4: "MESSAGE",
		5: "SUBSCRIBE_ROOM",
	}
	Command_value = map[string]int32{
		"UNKNOWN":        0,
		"SIGN_IN":        1,
		"SYNC":           2,
		"HEARTBEAT":      3,
		"MESSAGE":        4,
		"SUBSCRIBE_ROOM": 5,
	}
)

func (x Command) Enum() *Command {
	p := new(Command)
	*p = x
	return p
}

func (x Command) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Command) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_protocol_proto_connect_connect_ext_proto_enumTypes[0].Descriptor()
}

func (Command) Type() protoreflect.EnumType {
	return &file_pkg_protocol_proto_connect_connect_ext_proto_enumTypes[0]
}

func (x Command) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Command.Descriptor instead.
func (Command) EnumDescriptor() ([]byte, []int) {
	return file_pkg_protocol_proto_connect_connect_ext_proto_rawDescGZIP(), []int{0}
}

// 包
type Packet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       Command                `protobuf:"varint,1,opt,name=command,proto3,enum=connect.Command" json:"command,omitempty"` // 指令 说明了用于通信的数据包对应的服务类型
	RequestId     int64                  `protobuf:"varint,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // 请求id 用于解决异步请求时server端和客户端的请求响应匹配问题
	Code          uint32                 `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`                            // 错误码
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`                       // 错误信息
	Data          []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`                             // 数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_pkg_protocol_proto_connect_connect_ext_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_proto_connect_connect_ext_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_proto_connect_connect_ext_proto_rawDescGZIP(), []int{0}
}

func (x *Packet) GetCommand() Command {
	if x != nil {
		return x.Command
	}
	return Command_UNKNOWN
}

func (x *Packet) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *Packet) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Packet) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Packet) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 设备登录,package_type:1
type SignInInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      uint64                 `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"` // 设备id
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`       // 用户id
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`                        // 秘钥
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignInInput) Reset() {
	*x = SignInInput{}
	mi := &file_pkg_protocol_proto_connect_connect_ext_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInInput) ProtoMessage() {}

func (x *SignInInput) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_proto_connect_connect_ext_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInInput.ProtoReflect.Descriptor instead.
func (*SignInInput) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_proto_connect_connect_ext_proto_rawDescGZIP(), []int{1}
}

func (x *SignInInput) GetDeviceId() uint64 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *SignInInput) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SignInInput) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_pkg_protocol_proto_connect_connect_ext_proto protoreflect.FileDescriptor

const file_pkg_protocol_proto_connect_connect_ext_proto_rawDesc = "" +
	"\n" +
	",pkg/protocol/proto/connect/connect.ext.proto\x12\aconnect\"\x95\x01\n" +
	"\x06Packet\x12*\n" +
	"\acommand\x18\x01 \x01(\x0e2\x10.connect.CommandR\acommand\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\x03R\trequestId\x12\x12\n" +
	"\x04code\x18\x03 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\"Y\n" +
	"\vSignInInput\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\x04R\bdeviceId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token*]\n" +
	"\aCommand\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSIGN_IN\x10\x01\x12\b\n" +
	"\x04SYNC\x10\x02\x12\r\n" +
	"\tHEARTBEAT\x10\x03\x12\v\n" +
	"\aMESSAGE\x10\x04\x12\x12\n" +
	"\x0eSUBSCRIBE_ROOM\x10\x05B\x1bZ\x19pkg/protocol/pb/connectpbb\x06proto3"

var (
	file_pkg_protocol_proto_connect_connect_ext_proto_rawDescOnce sync.Once
	file_pkg_protocol_proto_connect_connect_ext_proto_rawDescData []byte
)

func file_pkg_protocol_proto_connect_connect_ext_proto_rawDescGZIP() []byte {
	file_pkg_protocol_proto_connect_connect_ext_proto_rawDescOnce.Do(func() {
		file_pkg_protocol_proto_connect_connect_ext_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_protocol_proto_connect_connect_ext_proto_rawDesc), len(file_pkg_protocol_proto_connect_connect_ext_proto_rawDesc)))
	})
	return file_pkg_protocol_proto_connect_connect_ext_proto_rawDescData
}

var file_pkg_protocol_proto_connect_connect_ext_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_protocol_proto_connect_connect_ext_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_protocol_proto_connect_connect_ext_proto_goTypes = []any{
	(Command)(0),        // 0: connect.Command
	(*Packet)(nil),      // 1: connect.Packet
	(*SignInInput)(nil), // 2: connect.SignInInput
}
var file_pkg_protocol_proto_connect_connect_ext_proto_depIdxs = []int32{
	0, // 0: connect.Packet.command:type_name -> connect.Command
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_protocol_proto_connect_connect_ext_proto_init() }
func file_pkg_protocol_proto_connect_connect_ext_proto_init() {
	if File_pkg_protocol_proto_connect_connect_ext_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_protocol_proto_connect_connect_ext_proto_rawDesc), len(file_pkg_protocol_proto_connect_connect_ext_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_protocol_proto_connect_connect_ext_proto_goTypes,
		DependencyIndexes: file_pkg_protocol_proto_connect_connect_ext_proto_depIdxs,
		EnumInfos:         file_pkg_protocol_proto_connect_connect_ext_proto_enumTypes,
		MessageInfos:      file_pkg_protocol_proto_connect_connect_ext_proto_msgTypes,
	}.Build()
	File_pkg_protocol_proto_connect_connect_ext_proto = out.File
	file_pkg_protocol_proto_connect_connect_ext_proto_goTypes = nil
	file_pkg_protocol_proto_connect_connect_ext_proto_depIdxs = nil
}
