// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: pkg/protocol/proto/logic/device.int.proto

package logicpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnSignInRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      uint64                 `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`      // 设备id
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`            // 用户id
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`                             // 秘钥
	ConnAddr      string                 `protobuf:"bytes,4,opt,name=conn_addr,json=connAddr,proto3" json:"conn_addr,omitempty"`       // 服务器地址 表示登录时connect层所在地址，用于room向设备发送消息
	ClientAddr    string                 `protobuf:"bytes,5,opt,name=client_addr,json=clientAddr,proto3" json:"client_addr,omitempty"` // 客户端地址
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnSignInRequest) Reset() {
	*x = ConnSignInRequest{}
	mi := &file_pkg_protocol_proto_logic_device_int_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnSignInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnSignInRequest) ProtoMessage() {}

func (x *ConnSignInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_proto_logic_device_int_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnSignInRequest.ProtoReflect.Descriptor instead.
func (*ConnSignInRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_proto_logic_device_int_proto_rawDescGZIP(), []int{0}
}

func (x *ConnSignInRequest) GetDeviceId() uint64 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *ConnSignInRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ConnSignInRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ConnSignInRequest) GetConnAddr() string {
	if x != nil {
		return x.ConnAddr
	}
	return ""
}

func (x *ConnSignInRequest) GetClientAddr() string {
	if x != nil {
		return x.ClientAddr
	}
	return ""
}

type OfflineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`            // 用户id
	DeviceId      uint64                 `protobuf:"varint,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`      // 设备id
	ClientAddr    string                 `protobuf:"bytes,3,opt,name=client_addr,json=clientAddr,proto3" json:"client_addr,omitempty"` // 客户端地址
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OfflineRequest) Reset() {
	*x = OfflineRequest{}
	mi := &file_pkg_protocol_proto_logic_device_int_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfflineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfflineRequest) ProtoMessage() {}

func (x *OfflineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_proto_logic_device_int_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfflineRequest.ProtoReflect.Descriptor instead.
func (*OfflineRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_proto_logic_device_int_proto_rawDescGZIP(), []int{1}
}

func (x *OfflineRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OfflineRequest) GetDeviceId() uint64 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *OfflineRequest) GetClientAddr() string {
	if x != nil {
		return x.ClientAddr
	}
	return ""
}

var File_pkg_protocol_proto_logic_device_int_proto protoreflect.FileDescriptor

const file_pkg_protocol_proto_logic_device_int_proto_rawDesc = "" +
	"\n" +
	")pkg/protocol/proto/logic/device.int.proto\x12\x05logic\x1a\x1bgoogle/protobuf/empty.proto\"\x9d\x01\n" +
	"\x11ConnSignInRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\x04R\bdeviceId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12\x1b\n" +
	"\tconn_addr\x18\x04 \x01(\tR\bconnAddr\x12\x1f\n" +
	"\vclient_addr\x18\x05 \x01(\tR\n" +
	"clientAddr\"g\n" +
	"\x0eOfflineRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\x04R\bdeviceId\x12\x1f\n" +
	"\vclient_addr\x18\x03 \x01(\tR\n" +
	"clientAddr2\x8c\x01\n" +
	"\x10DeviceIntService\x12>\n" +
	"\n" +
	"ConnSignIn\x12\x18.logic.ConnSignInRequest\x1a\x16.google.protobuf.Empty\x128\n" +
	"\aOffline\x12\x15.logic.OfflineRequest\x1a\x16.google.protobuf.EmptyB\x19Z\x17pkg/protocol/pb/logicpbb\x06proto3"

var (
	file_pkg_protocol_proto_logic_device_int_proto_rawDescOnce sync.Once
	file_pkg_protocol_proto_logic_device_int_proto_rawDescData []byte
)

func file_pkg_protocol_proto_logic_device_int_proto_rawDescGZIP() []byte {
	file_pkg_protocol_proto_logic_device_int_proto_rawDescOnce.Do(func() {
		file_pkg_protocol_proto_logic_device_int_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_protocol_proto_logic_device_int_proto_rawDesc), len(file_pkg_protocol_proto_logic_device_int_proto_rawDesc)))
	})
	return file_pkg_protocol_proto_logic_device_int_proto_rawDescData
}

var file_pkg_protocol_proto_logic_device_int_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_protocol_proto_logic_device_int_proto_goTypes = []any{
	(*ConnSignInRequest)(nil), // 0: logic.ConnSignInRequest
	(*OfflineRequest)(nil),    // 1: logic.OfflineRequest
	(*emptypb.Empty)(nil),     // 2: google.protobuf.Empty
}
var file_pkg_protocol_proto_logic_device_int_proto_depIdxs = []int32{
	0, // 0: logic.DeviceIntService.ConnSignIn:input_type -> logic.ConnSignInRequest
	1, // 1: logic.DeviceIntService.Offline:input_type -> logic.OfflineRequest
	2, // 2: logic.DeviceIntService.ConnSignIn:output_type -> google.protobuf.Empty
	2, // 3: logic.DeviceIntService.Offline:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_protocol_proto_logic_device_int_proto_init() }
func file_pkg_protocol_proto_logic_device_int_proto_init() {
	if File_pkg_protocol_proto_logic_device_int_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_protocol_proto_logic_device_int_proto_rawDesc), len(file_pkg_protocol_proto_logic_device_int_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_protocol_proto_logic_device_int_proto_goTypes,
		DependencyIndexes: file_pkg_protocol_proto_logic_device_int_proto_depIdxs,
		MessageInfos:      file_pkg_protocol_proto_logic_device_int_proto_msgTypes,
	}.Build()
	File_pkg_protocol_proto_logic_device_int_proto = out.File
	file_pkg_protocol_proto_logic_device_int_proto_goTypes = nil
	file_pkg_protocol_proto_logic_device_int_proto_depIdxs = nil
}
