// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dao

import (
	"database/sql"
	"encoding/json"
	"time"
)

// 设备
type Device struct {
	// 自增主键
	ID uint64 `json:"id"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at"`
	// 账户id
	UserID uint64 `json:"user_id"`
	// 设备类型,1:Android；2：IOS；3：Windows; 4：MacOS；5：Web
	Type int8 `json:"type"`
	// 手机厂商
	Brand string `json:"brand"`
	// 机型
	Model string `json:"model"`
	// 系统版本
	SystemVersion string `json:"system_version"`
	// app版本
	SdkVersion string `json:"sdk_version"`
	// 在线状态，0：离线；1：在线
	Status int8 `json:"status"`
	// 连接层服务器地址
	ConnAddr string `json:"conn_addr"`
	// 客户端地址
	ClientAddr string `json:"client_addr"`
}

// 好友关系表
type Friend struct {
	// 自增主键
	ID uint64 `json:"id"`
	// 用户ID
	UserID uint64 `json:"user_id"`
	// 好友用户ID
	FriendID uint64 `json:"friend_id"`
	// 好友备注
	Remark string `json:"remark"`
	// 好友分类ID，0为默认分组
	CategoryID uint64 `json:"category_id"`
	// 是否屏蔽：0-否，1-是
	IsBlocked int8 `json:"is_blocked"`
	// 添加时间
	CreatedAt time.Time `json:"created_at"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at"`
}

// 好友申请表
type FriendRequest struct {
	// 自增主键
	ID uint64 `json:"id"`
	// 申请人用户ID
	RequesterID uint64 `json:"requester_id"`
	// 接收人用户ID
	RecipientID uint64 `json:"recipient_id"`
	// 状态：0-待处理，1-已同意，2-已拒绝，3-已忽略
	Status int8 `json:"status"`
	// 验证消息
	Message string `json:"message"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at"`
}

// 群组
type Group struct {
	// 自增主键
	ID uint64 `json:"id"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at"`
	// 群组名称
	Name string `json:"name"`
	// 群组头像
	AvatarUrl string `json:"avatar_url"`
	// 群组简介
	Introduction string `json:"introduction"`
	// 群组人数
	UserNum int32 `json:"user_num"`
	// 附加属性
	Extra string `json:"extra"`
}

// 群组成员
type GroupUser struct {
	// 组id
	GroupID uint64 `json:"group_id"`
	// 用户id
	UserID uint64 `json:"user_id"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at"`
	// 成员类型，1：管理员；2：普通成员
	MemberType int8 `json:"member_type"`
	// 备注
	Remarks string `json:"remarks"`
	// 附加属性
	Extra string `json:"extra"`
	// 状态
	Status int8 `json:"status"`
}

// 消息
type Message struct {
	// 自增主键
	ID uint64 `json:"id"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at"`
	// 请求id
	RequestID int64 `json:"request_id"`
	// 消息类型
	Code int32 `json:"code"`
	// 消息内容
	Content []byte `json:"content"`
	// 消息状态，0：未处理1：消息撤回
	Status int8 `json:"status"`
}

// 序列号
type Seq struct {
	// 自增主键
	ID uint64 `json:"id"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at"`
	// 对象类型,1:用户；2：群组
	ObjectType int8 `json:"object_type"`
	// 对象id
	ObjectID uint64 `json:"object_id"`
	// 序列号
	Seq uint64 `json:"seq"`
}

// 用户表
type User struct {
	// 自增主键
	ID uint64 `json:"id"`
	// 用户名，唯一
	Username string `json:"username"`
	// 哈希后的密码
	HashedPassword string `json:"hashed_password"`
	// 昵称
	Nickname string `json:"nickname"`
	// 性别，0:未知；1:男；2:女
	Sex int8 `json:"sex"`
	// 用户头像链接
	AvatarUrl string `json:"avatar_url"`
	// 邮箱，唯一
	Email sql.NullString `json:"email"`
	// 手机号，唯一
	PhoneNumber sql.NullString `json:"phone_number"`
	// 用户状态，1:正常；2:禁用；3:已注销(逻辑删除)
	Status int8 `json:"status"`
	// 附加属性，存储非结构化数据
	Extra json.RawMessage `json:"extra"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at"`
}

// 用户消息
type UserMessage struct {
	// 所属类型的id
	UserID uint64 `json:"user_id"`
	// 消息序列号
	Seq uint64 `json:"seq"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at"`
	// 消息ID
	MessageID uint64 `json:"message_id"`
}
